### ISSUE TITLE
haplodmf.sh: line 497: 71399 killed

### ISSUE THREAD

**Issue by HarshitKrPrajapati** [dhcai21/HaploDMF#1]
Hello,

I am trying to use the tool for my long-read sequencing data from the ONT MinION platform. I had mapped the reads using minimap2 and had given the same SAM file as input, however, the process has been failing with the following error.
I am very new to using Anaconda, so maybe I am making some basic mistakes. Can anyone help me out?

job file:-

#!/bin/bash

#SBATCH --job-name=haplodmf
#SBATCH --mail-user=myemail
#SBATCH --mail-type=end
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=8000
#SBATCH --time=24:00:00
#SBATCH --qos=standard
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1

cd /myfolder/HaploDMF/
module add Anaconda3
source activate
conda activate /myfolder/anac/haplodmf
module add medaka
module add SAMtools
bash haplodmf.sh -i /myfolder/SUP_basecalling/input.sam -r /myfolder/SUP_basecalling/reference.fasta -o /myfolder/SUP_basecalling/result

slurm out:-

count nucleotide occurrence
[bam_sort_core] merging from 13 files and 1 in-memory blocks...
SNV detection
first binomial test

  0%|          | 0/10112 [00:00<?, ?it/s]
  4%|â–         | 388/10112 [00:00<00:02, 3858.99it/s]
  8%|â–Š         | 774/10112 [00:00<00:02, 3771.54it/s]
 11%|â–ˆâ–        | 1152/10112 [00:00<00:02, 3742.14it/s]
 15%|â–ˆâ–Œ        | 1527/10112 [00:00<00:02, 3716.61it/s]
 19%|â–ˆâ–‰        | 1900/10112 [00:00<00:02, 3719.53it/s]
 23%|â–ˆâ–ˆâ–Ž       | 2278/10112 [00:00<00:02, 3731.45it/s]
 26%|â–ˆâ–ˆâ–‹       | 2665/10112 [00:00<00:01, 3759.71it/s]
 30%|â–ˆâ–ˆâ–ˆ       | 3043/10112 [00:00<00:01, 3742.94it/s]
 34%|â–ˆâ–ˆâ–ˆâ–      | 3421/10112 [00:00<00:01, 3728.19it/s]
 38%|â–ˆâ–ˆâ–ˆâ–Š      | 3808/10112 [00:01<00:01, 3759.39it/s]
 42%|â–ˆâ–ˆâ–ˆâ–ˆâ–     | 4198/10112 [00:01<00:01, 3784.11it/s]
 45%|â–ˆâ–ˆâ–ˆâ–ˆâ–Œ     | 4585/10112 [00:01<00:01, 3806.63it/s]
 49%|â–ˆâ–ˆâ–ˆâ–ˆâ–‰     | 4972/10112 [00:01<00:01, 3811.52it/s]
 53%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž    | 5359/10112 [00:01<00:01, 3812.92it/s]
 57%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹    | 5755/10112 [00:01<00:01, 3834.26it/s]
 61%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ    | 6139/10112 [00:01<00:01, 3823.02it/s]
 64%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–   | 6522/10112 [00:01<00:00, 3701.18it/s]
 69%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š   | 6943/10112 [00:01<00:00, 3832.20it/s]
 72%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–  | 7327/10112 [00:01<00:00, 3813.25it/s]
 76%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹  | 7717/10112 [00:02<00:00, 3834.53it/s]
 80%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 8104/10112 [00:02<00:00, 3827.94it/s]
 84%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ– | 8491/10112 [00:02<00:00, 3836.54it/s]
 88%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š | 8878/10112 [00:02<00:00, 3828.55it/s]
 92%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–| 9265/10112 [00:02<00:00, 3824.71it/s]
 96%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ| 9661/10112 [00:02<00:00, 3843.07it/s]
 99%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 10057/10112 [00:02<00:00, 3856.81it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10112/10112 [00:02<00:00, 3802.45it/s]
second binomial test

  0%|          | 0/10112 [00:00<?, ?it/s]
  1%|          | 64/10112 [00:00<00:15, 633.99it/s]
  4%|â–         | 433/10112 [00:00<00:04, 2411.52it/s]
  8%|â–Š         | 802/10112 [00:00<00:03, 2990.41it/s]
 12%|â–ˆâ–        | 1180/10112 [00:00<00:02, 3275.23it/s]
 15%|â–ˆâ–Œ        | 1549/10112 [00:00<00:02, 3412.16it/s]
 19%|â–ˆâ–‰        | 1918/10112 [00:00<00:02, 3481.74it/s]
 23%|â–ˆâ–ˆâ–Ž       | 2287/10112 [00:00<00:02, 3533.04it/s]
 26%|â–ˆâ–ˆâ–‹       | 2656/10112 [00:00<00:02, 3556.03it/s]
 30%|â–ˆâ–ˆâ–‰       | 3012/10112 [00:00<00:02, 3492.01it/s]
 33%|â–ˆâ–ˆâ–ˆâ–Ž      | 3367/10112 [00:01<00:01, 3499.49it/s]
 37%|â–ˆâ–ˆâ–ˆâ–‹      | 3736/10112 [00:01<00:01, 3544.44it/s]
 41%|â–ˆâ–ˆâ–ˆâ–ˆ      | 4105/10112 [00:01<00:01, 3578.08it/s]
 44%|â–ˆâ–ˆâ–ˆâ–ˆâ–     | 4466/10112 [00:01<00:01, 3569.39it/s]
 48%|â–ˆâ–ˆâ–ˆâ–ˆâ–Š     | 4826/10112 [00:01<00:01, 3563.69it/s]
 51%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–    | 5195/10112 [00:01<00:01, 3590.72it/s]
 55%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ    | 5564/10112 [00:01<00:01, 3602.65it/s]
 59%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š    | 5925/10112 [00:01<00:01, 3601.93it/s]
 62%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–   | 6293/10112 [00:01<00:01, 3620.85it/s]
 66%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Œ   | 6662/10112 [00:01<00:00, 3629.69it/s]
 69%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰   | 7025/10112 [00:02<00:00, 3626.60it/s]
 73%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Ž  | 7392/10112 [00:02<00:00, 3621.42it/s]
 77%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹  | 7755/10112 [00:02<00:00, 3619.77it/s]
 80%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ  | 8121/10112 [00:02<00:00, 3619.45it/s]
 84%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ– | 8490/10112 [00:02<00:00, 3637.99it/s]
 88%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š | 8859/10112 [00:02<00:00, 3646.85it/s]
 91%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ | 9224/10112 [00:02<00:00, 3627.12it/s]
 95%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–| 9588/10112 [00:02<00:00, 3622.16it/s]
 99%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–Š| 9966/10112 [00:02<00:00, 3645.94it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 10112/10112 [00:02<00:00, 3518.32it/s]
haplodmf.sh: line 497: 71399 Killed                  python ./src/fre_matrix.py $file_bam_sorted $file_snv $file_prefix $cond_pro $smallest_snv $num_read_1 $num_read_2 $gap $fre_snv $thread $input_snv
Deep matrix factorization training and clustering
Traceback (most recent call last):
  File "/myfolder/HaploDMF/./src/dmf.py", line 4, in <module>
    import torch.nn.functional as F
ModuleNotFoundError: No module named 'torch'
haplotypes reconstruction
Traceback (most recent call last):
  File "/myfolder/HaploDMF/./src/out_haplotypes.py", line 51, in <module>
    f = open(file_clusters,'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/myfolder/SUP_basecalling/result/haplodmf_clusters.pickle'
haplotypes polishment (medaka)
Traceback (most recent call last):
  File "/myfolder/HaploDMF/./src/extract_reads.py", line 20, in <module>
    for seq in SeqIO.parse(file,'fasta'):
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/myfolder/SUP_basecalling/result/haplodmf_consensus.fasta'
Traceback (most recent call last):
  File "/myfolder/HaploDMF/./src/run_medaka.py", line 17, in <module>
    for seq in SeqIO.parse(file,'fasta'):
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/trinity/shared/easybuild/software/Biopython/1.79-foss-2021a/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/myfolder/SUP_basecalling/result/haplodmf_consensus.fasta'
rm: cannot remove '/myfolder/SUP_basecalling/result/haplodmf_matrix.pickle': No such file or directory
rm: cannot remove '/scratch/hp3508fu/S11_DWV/S11_DWV_Parent/S11/20221216_0334_MN39055_FAR95232_50fb5fcd/SUP_basecalling/haplodmf/result/haplodmf_clusters.pickle': No such file or directory
Finished
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=12859523.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

== Epilog Slurmctld ==================================================

Job ID: 12859523
State: OUT_OF_MEMORY (exit code 0)
Cores: 1
CPU Utilized: 02:52:12
CPU Efficiency: 36.13% of 07:56:36 core-walltime
Job Wall-clock time: 07:56:36
Memory Utilized: 7.81 GB
Memory Efficiency: 100.00% of 7.81 GB

======================================================================

**Comment by dhcai21** [comment]
Hello,

Thank you for reporting this issue. The error message you are seeing, "Some of your processes may have been killed by the cgroup out-of-memory handler," typically indicates that your system does not have enough memory to complete the operation. This can often be resolved by increasing the amount of memory available to your system.

Additionally, the second error, "No module named 'torch'," suggests that the PyTorch library is not installed on your system. Please ensure that you have installed PyTorch and have properly configured it before running your code again.

If you continue to experience issues, please feel free to email me with any further questions or details about your setup.

Dehan

**Comment by hpironhide** [comment]
Hi Dehan,

Thank you for guiding me through it.
I checked it and the pytorch was installed. However, failed to import.
Could it be because of the older versions of packages in the provided YAML file?

Thank you.
Harshit

**Comment by dhcai21** [comment]
Hi Harshit,

Could you please let me know which version of PyTorch you are currently using? Additionally, please provide me with a screenshot or details of your current environment. For reference, I am currently using "pytorch=1.10.0=py3.8_cuda11.1_cudnn8.0.5_0". 

Dehan

**Comment by dhcai21** [comment]
Hi,

To resolve the issue with importing PyTorch, you can try uninstalling the current version and reinstalling a new one from the official PyTorch website, which can be found at "https://pytorch.org/". If you are using an HPC system, you can use the "nvcc --version" command to check which version of CUDA is suitable for your system, and then install PyTorch with the corresponding CUDA version.

I hope this helps! Let me know if you have any further questions.

Dehan

**Comment by hpironhide** [comment]
Hi Dehan,

I am working on a HPC.

I tried removing the existing environment, and create a new one using the commands:-
$ module add Anaconda3
$ source activate
$ conda env create -f /path/to/HaploDMF/directory/haplodmf.yaml -n haplodmf

However, I got many conflict warnings. Please see below for a few including PyTorch:-
-------------------------------------------------------------------------------------------------------------------------------------------
Package pytorch conflicts for:
pytorch==1.10.0=py3.8_cuda11.1_cudnn8.0.5_0
torchvision==0.11.1=py38_cu111 -> pytorch==1.10.0
torchaudio==0.10.0=py38_cu111 -> pytorch==1.10.0

Package whatshap conflicts for:
whatshap==1.4=py38h4a32c8e_0
medaka==1.6.1=py38h84d2cc8_0 -> whatshap[version='>=0.18']

Package tensorboard-data-server conflicts for:
tensorboard-data-server==0.6.0=py38h2b5fc30_2
tensorflow==2.2.0=mkl_py38h6d3daf0_0 -> tensorboard[version='>=2.2.0'] -> tensorboard-data-server[version='>=0.6.0,<0.7.0|>=0.7.0,<0.8.0']
tensorboard==2.9.0=pyhd8ed1ab_0 -> tensorboard-data-server[version='>=0.6.0,<0.7.0']

Package ffmpeg conflicts for:
torchvision==0.11.1=py38_cu111 -> ffmpeg[version='>=4.2']
ffmpeg==4.3=hf484d3e_0

Package libwebp conflicts for:
pillow==9.2.0=py38h0ee0e06_0 -> libwebp
torchvision==0.11.1=py38_cu111 -> pillow[version='>=5.3.0'] -> libwebp[version='>=0.3.0|>=1.2.0,<1.3.0a0']
libwebp==1.2.2=h3452ae3_0
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.17=0
  - feature:|@/linux-64::__unix==0=0
  - abseil-cpp==20211102.0=h27087fc_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - aiohttp==3.8.1=py38h0a891b7_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - bcftools==1.15.1=h0ea216a_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - brotlipy==0.7.0=py38h0a891b7_1004 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - bzip2==1.0.8=h7f98852_4 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - c-ares==1.18.1=h7f98852_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - cudatoolkit==11.1.1=ha002fc5_10 -> __glibc[version='>=2.17,<3.0.a0']
  - cudatoolkit==11.1.1=ha002fc5_10 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - ffmpeg==4.3=hf484d3e_0 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - freetype==2.10.4=h0708190_1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - frozenlist==1.3.0=py38h0a891b7_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - giflib==5.2.1=h36c2ea0_2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gmp==6.2.1=h58526e2_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gnutls==3.6.13=h85f3911_1 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - google-auth-oauthlib==0.4.6=pyhd8ed1ab_0 -> click[version='>=6.0.0'] -> __unix
  - google-auth-oauthlib==0.4.6=pyhd8ed1ab_0 -> click[version='>=6.0.0'] -> __win
  - gsl==2.7=he838d99_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - h5py==2.10.0=nompi_py38h9915d05_106 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - hdf5==1.10.6=nompi_h6a2412b_1114 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - htslib==1.15.1=h9753748_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - isa-l==2.30.0=ha770c72_4 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - k8==0.2.5=hd03093a_2 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - keyutils==1.6.1=h166bdaf_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - krb5==1.19.3=h3790be6_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - lame==3.100=h7f98852_1001 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lcms2==2.12=hddcbb42_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - lerc==3.0=h9c3ff4c_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libcurl==7.83.1=h7bff187_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - libdeflate==1.10=h7f98852_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libedit==3.1.20191231=he28a2e2_2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libev==4.33=h516909a_1 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libffi==3.4.2=h7f98852_5 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libiconv==1.16=h516909a_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libnghttp2==1.47.0=h727a467_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - libnsl==2.0.0=h7f98852_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libopenblas==0.3.20=pthreads_h78a6416_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - libprotobuf==3.20.1=h6239696_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - libssh2==1.10.0=ha56f1ee_2 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libuuid==2.32.1=h7f98852_1000 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libuv==1.43.0=h7f98852_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libwebp-base==1.2.2=h7f98852_1 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libwebp==1.2.2=h3452ae3_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - libxcb==1.13=h7f98852_1004 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - lz4-c==1.9.3=h9c3ff4c_1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mappy==2.24=py38h4c6a040_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - minimap2==2.24=h7132678_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - multidict==6.0.2=py38h0a891b7_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - ncurses==6.3=h27087fc_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - nettle==3.6=he412f7d_0 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - numpy==1.19.5=py38h8246c76_3 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - openh264==2.1.1=h780b84a_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - openjpeg==2.4.0=hb52868f_1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - parasail-python==1.2.4=py38h3b68952_2 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - perl==5.32.1=2_h7f98852_perl5 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - pigz==2.6=h27826a3_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - protobuf==3.20.1=py38hfa26641_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - pthread-stubs==0.4=h36c2ea0_1001 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pyspoa==0.0.3=py38h8ded8fe_3 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - python-edlib==1.3.9=py38h4a32c8e_1 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - python-isal==0.11.1=py38h497a2fe_1 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - python==3.8.13=h582c2e5_0_cpython -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - pytorch==1.10.0=py3.8_cuda11.1_cudnn8.0.5_0 -> cudatoolkit[version='>=11.1,<11.2'] -> __glibc[version='>=2.17,<3.0.a0']
  - samtools==1.15.1=h1170115_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - scipy==1.8.1=py38h1ee437e_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - tar==1.34=ha1f6473_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - tensorboard-data-server==0.6.0=py38h2b5fc30_2 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - tensorflow-base==2.2.0=mkl_py38h5059a2d_0 -> libgcc-ng[version='>=5.4.0'] -> __glibc[version='>=2.17']
  - tensorflow-estimator==2.6.0=py38h709712a_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - tensorflow==2.2.0=mkl_py38h6d3daf0_0 -> tensorflow-estimator[version='>=2.2.0'] -> __glibc[version='>=2.17']
  - tk==8.6.12=h27826a3_0 -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']
  - torchaudio==0.10.0=py38_cu111 -> cudatoolkit[version='>=11.1,<11.2'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchvision==0.11.1=py38_cu111 -> cudatoolkit[version='>=11.1,<11.2'] -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - urllib3==1.26.10=pyhd8ed1ab_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __unix
  - urllib3==1.26.10=pyhd8ed1ab_0 -> pysocks[version='>=1.5.6,<2.0,!=1.5.7'] -> __win
  - whatshap==1.4=py38h4a32c8e_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - wrapt==1.14.1=py38h0a891b7_0 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
  - xorg-libxau==1.0.9=h7f98852_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xorg-libxdmcp==1.1.3=h7f98852_0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - xz==5.2.5=h516909a_1 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - yarl==1.7.2=py38h0a891b7_2 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17

Note that strict channel priority may have removed packages required for satisfiability.
---------------------------------------------------------------------------------------------------------------------------------

I could check for PyTorch individually as well.

**Comment by dhcai21** [comment]
Hello!

You can install different versions of PyTorch, as long as they are compatible with your system and other dependencies. 

You can also create a new conda environment and specifying the desired version of PyTorch using the `conda install` command. You can find more details in the README file.

Here's an example of how to set up the environment for HaploDMF:

```
conda create -n haplodmf python=3.8.
conda activate haplodmf
conda install -c bioconda -c conda-forge medaka
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia  (# Install the correct version of PyTorch for your system: https://pytorch.org/)
pip install sklearn pandas tqdm
```

The specific version of PyTorch you should install may depend on your system and other requirements. You can check the PyTorch website for more information on compatibility and installation options.

I hope this helps! Feel free to let me know if you have any more questions.

Dehan
