### ISSUE TITLE
License of HaploDMF

### ISSUE THREAD

**Issue by RolandFaure** [dhcai21/HaploDMF#3]
Hello,
I like very much HaploDMF, I ran it on a personnal dataset and it provided stunning results. I was wondering if you would consider attaching a license to HaploDMF. I am personnaly working on the haplotyping of bacteria, and I would love to try to adapt part of the HaploDMF code in this context, if you allow it.

**Comment by dhcai21** [comment]
Hi,

It's great to hear that HaploDMF is working well for your dataset! I've uploaded the license. Feel free to use the code for your own project, and let me know if you have any further questions or require additional assistance.

I would greatly appreciate it if you cited our paper when using HaploDMF. Your support and acknowledgment will help the continued development of the tool.

Best regards,
Dehan

**Comment by RolandFaure** [comment]
Thanks !
If I use a part of haploDMF I will obviously cite it :grin:
