### ISSUE TITLE
ModelStore exception <class 'NotImplementedError'>

### ISSUE THREAD

**Issue by RPHdejongh** [dhcai21/HaploDMF#4]
Hi, 

I wanted to try out your tool, but I'm running into some problems. I can not even get the tested_data example to work. I used the following command to try after doing git clone from your repo.

```bash
./haplodmf.sh -i tested_data/test.sam -r tested_data/reference.fasta -o test_result -p test > stdout.txt 2> stderr.txt
```

I've included the stderr, stdout and the mamba env export output to indicate the environment I'm working with. Since the stderr lists something about ModelStore I thought it might be related to a too-new version of PyTorch so I downgraded from 2.0.1 to 1.13.1. But that also didn't do the trick.

[stderr.txt](https://github.com/dhcai21/HaploDMF/files/12749131/stderr.txt)
[stdout.txt](https://github.com/dhcai21/HaploDMF/files/12749133/stdout.txt)
[env.yml.txt](https://github.com/dhcai21/HaploDMF/files/12749148/env.yml.txt)

Any help would be appreciated, thank you!
Ronald

**Comment by dhcai21** [comment]
Hi,

Based on your provided information, the error only occurred in the final step (polishment) using Medaka. Your Medaka version is 1.2.2, while mine is 1.6.0. Please reinstall Medaka with a version >= 1.6.0 to see if it works. I have attached my environment for your reference.
 
[haplodmf.yml.zip](https://github.com/dhcai21/HaploDMF/files/12749850/haplodmf.yml.zip)

If you have any questions, feel free to message me. I will reply to you as soon as possible.

Dehan

**Comment by dhcai21** [comment]
Please check whether there is an output file called "*_consensus.fasta". This file contains the consensus sequences (haplotypes) generated directly from read clusters. Afterward, Medaka will polish these sequences to improve their quality. If the file exists and is not empty, the error indeed only occurs in the polishment step.

Dehan

**Comment by RPHdejongh** [comment]
Hi Dehan, 

I installed Medaka 1.8.0 and that did the trick for the test data, thanks! Will try on my own data because there was some other issue there and let you know of any problems.

By the way I also noticed that BioPython was required, but it wasn't listed in the installation instructions. What version do you recommend? 

Ronald

**Comment by dhcai21** [comment]
I am using the version of 1.79. You can use this one. 

Dehan

**Comment by RPHdejongh** [comment]
Got it to work on my own data as well, thanks!
